a=int(input("Enter the fist number.\n"))
b=int(input("Enter the second number.\n"))
c=int(input("Enter the third number.\n"))
if (a>b) and (a>c):
        print("The greatest number is",a)
if (b>a) and (b>c):
        print("The greatest number is",b)
if (c>a) and (c>b):
    print("The greatest number is",c)